---

- name: Install gitlab runner
  hosts: all
  become: true

  vars:
    gitlab_runner_registration_token: ''
    gitlab_runner_connect_enable: false

    #Gauntlt needs ruby installed
    ruby_version: 'ruby-2.3.1'
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_user: 'root'
    rvm1_install_path: '/usr/local/rvm'

  roles:
    - common
    - rvm_io.ruby
    - secfigo.gauntlt
    - geerlingguy.docker
    - gitlab-runner
    - geerlingguy.ansible-role-packer
    - secfigo.terraform
    - python
    - cli-tools
  tags:
    - runner
